apiVersion: v1
kind: Service
metadata:
  name: go-web-app
  labels:
    app: go-web-app
spec:
  type: NodePort  # Change the type to NodePort to expose the service externally
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: go-web-app  # Correct placement of the selector
